# Generated by Django 3.0.1 on 2019-12-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtonet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChassisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='carad',
            name='avtonetId',
        ),
        migrations.AddField(
            model_name='carad',
            name='ad_published_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='avtonet_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='cover_photo_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='driven_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='engine_power_kw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='engine_volume_ccm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='features',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='first_registration_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='last_fully_crawled_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='number_of_gears',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='safety_inspection_until',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='today_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='first_seen_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carad',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='AdData',
        ),
        migrations.AddField(
            model_name='carad',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.EngineType'),
        ),
        migrations.AddField(
            model_name='carad',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.TransmissionType'),
        ),
    ]
