# Generated by Django 3.0.1 on 2019-12-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtonet', '0002_auto_20191218_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='ad_published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='avtonet_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='cover_photo_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='driven_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='engine_power_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='engine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.EngineType'),
        ),
        migrations.AlterField(
            model_name='carad',
            name='engine_volume_ccm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='first_registration_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='last_fully_crawled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='number_of_gears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='safety_inspection_until',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='carad',
            name='today_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carad',
            name='transmission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.TransmissionType'),
        ),
    ]
