# Generated by Django 3.0.1 on 2019-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtonet', '0003_auto_20191218_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='first_seen_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
