# Generated by Django 3.0.1 on 2019-12-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtonet', '0005_auto_20191218_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='carad',
            old_name='safety_inspection_until',
            new_name='safety_inspection_until_year',
        ),
        migrations.AddField(
            model_name='carad',
            name='chassis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.ChassisType'),
        ),
        migrations.AddField(
            model_name='carad',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='cover_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='carad',
            name='safety_inspection_until_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avtonet.AgeType'),
        ),
    ]
